apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: norge360-auth-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: norge360-auth-api
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: norge360-gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: norge360-gateway
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: norge360-accounts-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: norge360-accounts-api
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: norge360-community-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: norge360-community-api
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: norge360-discovery-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: norge360-discovery-api
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: norge360-search-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: norge360-search-api
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
