apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: norge360-production

resources:
  - namespace.yaml
  - services.yaml
  - deployments.yaml
  - statefulsets.yaml
  - redis.yaml
  - horizontalpodautoscalers.yaml
  - poddisruptionbudgets.yaml
  - networkpolicies.yaml
  - ingress.yaml
