// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Norge360.MessagingService.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Norge360.MessagingService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MessagingDbContext))]
    [Migration("20260607181644_InitialMessagingSchema")]
    partial class InitialMessagingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Norge360.MessagingService.Domain.Entities.MessagingConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("DefaultDisappearingTtlSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastMessageAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LastMessageSenderUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Status", "LastMessageAtUtc");

                    b.ToTable("MessagingConversations", (string)null);
                });

            modelBuilder.Entity("Norge360.MessagingService.Domain.Entities.MessagingConversationParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BackgroundKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("ClearedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastDeliveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastDeliveredMessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastReadAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastReadMessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LeftAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("MarkedUnreadAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("MutedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("NicknameCipherText")
                        .HasColumnType("bytea");

                    b.Property<string>("NicknameKeyId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<byte[]>("NicknameNonce")
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("PinnedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("ThemeKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "UserId")
                        .IsUnique();

                    b.HasIndex("UserId", "DeletedAtUtc", "LeftAtUtc");

                    b.HasIndex("UserId", "PinnedAtUtc", "ArchivedAtUtc");

                    b.ToTable("MessagingConversationParticipants", (string)null);
                });

            modelBuilder.Entity("Norge360.MessagingService.Domain.Entities.MessagingConversationReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceKeyId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("ReportedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReporterUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<byte[]>("UserProvidedEvidenceCipherText")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("UserProvidedEvidenceNonce")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("ConversationId", "CreatedAtUtc");

                    b.HasIndex("ReporterUserId", "CreatedAtUtc");

                    b.ToTable("MessagingConversationReports", (string)null);
                });

            modelBuilder.Entity("Norge360.MessagingService.Domain.Entities.MessagingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssociatedDataJson")
                        .HasColumnType("text");

                    b.Property<int>("AttachmentCount")
                        .HasColumnType("integer");

                    b.Property<string>("CipherKeyId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<byte[]>("CipherNonce")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("CipherText")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ClientMessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ClientSearchTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DisappearingTtlSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EditUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EditedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptionAlgorithm")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FirstViewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ForwardedFromConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ForwardedFromMessageId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsForwarded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RecallUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RecalledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplyToMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("SenderDeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SharedPostId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<bool>("ViewOnce")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("ReplyToMessageId");

                    b.HasIndex("SharedPostId");

                    b.HasIndex("ConversationId", "ClientSearchTokenHash");

                    b.HasIndex("ConversationId", "CreatedAtUtc");

                    b.HasIndex("ConversationId", "SenderUserId", "ClientMessageId")
                        .IsUnique();

                    b.ToTable("MessagingMessages", (string)null);
                });

            modelBuilder.Entity("Norge360.MessagingService.Domain.Entities.MessagingMessageAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<byte[]>("EncryptedFileKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<byte[]>("KeyNonce")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("ViewOnce")
                        .HasColumnType("boolean");

                    b.Property<string>("WaveformJson")
                        .HasColumnType("text");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "CreatedAtUtc");

                    b.HasIndex("MessageId", "Kind");

                    b.ToTable("MessagingMessageAttachments", (string)null);
                });

            modelBuilder.Entity("Norge360.MessagingService.Domain.Entities.MessagingMessageReaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MessageId", "UserId", "Emoji")
                        .IsUnique();

                    b.ToTable("MessagingMessageReactions", (string)null);
                });

            modelBuilder.Entity("Norge360.MessagingService.Domain.Entities.MessagingMessageReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeliveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MessageId", "UserId")
                        .IsUnique();

                    b.HasIndex("UserId", "ReadAtUtc");

                    b.ToTable("MessagingMessageReceipts", (string)null);
                });

            modelBuilder.Entity("Norge360.MessagingService.Domain.Entities.MessagingUserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OneTimePreKeysJson")
                        .HasColumnType("text");

                    b.Property<string>("PublicIdentityKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SignedPreKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("SignedPreKeySignature")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("SupportedAlgorithms")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DeviceId")
                        .IsUnique();

                    b.HasIndex("UserId", "RevokedAtUtc");

                    b.ToTable("MessagingUserDevices", (string)null);
                });

            modelBuilder.Entity("Norge360.MessagingService.Domain.Entities.MessagingUserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("GroupInvitePermission")
                        .HasColumnType("integer");

                    b.Property<bool>("LinkPreviewsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("MessagePermission")
                        .HasColumnType("integer");

                    b.Property<int>("OnlineVisibility")
                        .HasColumnType("integer");

                    b.Property<bool>("ReadReceiptsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowMessagePreviewInNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("TypingIndicatorsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("MessagingUserSettings", (string)null);
                });

            modelBuilder.Entity("Norge360.MessagingService.Domain.Entities.MessagingConversationParticipant", b =>
                {
                    b.HasOne("Norge360.MessagingService.Domain.Entities.MessagingConversation", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Norge360.MessagingService.Domain.Entities.MessagingMessage", b =>
                {
                    b.HasOne("Norge360.MessagingService.Domain.Entities.MessagingConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Norge360.MessagingService.Domain.Entities.MessagingMessageAttachment", b =>
                {
                    b.HasOne("Norge360.MessagingService.Domain.Entities.MessagingMessage", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Norge360.MessagingService.Domain.Entities.MessagingMessageReaction", b =>
                {
                    b.HasOne("Norge360.MessagingService.Domain.Entities.MessagingMessage", "Message")
                        .WithMany("Reactions")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Norge360.MessagingService.Domain.Entities.MessagingMessageReceipt", b =>
                {
                    b.HasOne("Norge360.MessagingService.Domain.Entities.MessagingMessage", "Message")
                        .WithMany("Receipts")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Norge360.MessagingService.Domain.Entities.MessagingConversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Norge360.MessagingService.Domain.Entities.MessagingMessage", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Reactions");

                    b.Navigation("Receipts");
                });
#pragma warning restore 612, 618
        }
    }
}
