// <copyright file="NamespaceArchitectureTests.cs" company="Norge360">
// Copyright (c) 2026 Norge360. All rights reserved.
// Norge360 is proprietary software. See the LICENSE file in the repository root.
// </copyright>

namespace Norge360.AspNetCore.CurrentUser.Architecture.Tests;

public class NamespaceArchitectureTests
{
    [Fact]
    public void Production_types_should_live_under_root_namespace()
    {
        var violations = ArchitectureAssertions.GetProductionTypes()
            .Where(type => type.Namespace is null || !type.Namespace.StartsWith("Norge360.AspNetCore.CurrentUser", StringComparison.Ordinal))
            .Select(type => type.FullName ?? type.Name);

        ArchitectureAssertions.AssertNoViolations(
            violations,
            "All production types should live under Norge360.AspNetCore.CurrentUser root namespace");
    }

    [Fact]
    public void Test_types_should_live_under_test_namespace()
    {
        var testAssembly = typeof(NamespaceArchitectureTests).Assembly;
        var violations = testAssembly
            .GetTypes()
            .Where(type => !type.Name.Equals("AutoGeneratedProgram", StringComparison.Ordinal))
            .Where(type => type.Namespace is null || !type.Namespace.StartsWith("Norge360.AspNetCore.CurrentUser.Architecture.Tests", StringComparison.Ordinal))
            .Select(type => type.FullName ?? type.Name);

        ArchitectureAssertions.AssertNoViolations(
            violations,
            "All test types should live under Norge360.AspNetCore.CurrentUser.Architecture.Tests namespace");
    }
}
